src/Entity/Resource.php
<?php

namespace App\Entity;

use App\Repository\ResourceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ResourceRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Resource
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ressources")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Pathology::class, inversedBy="ressources")
     */
    private $pathology;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=ResourceFormat::class, inversedBy="ressources")
     * @ORM\JoinColumn(nullable=false)
     */
    private $resourceFormat;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\OneToMany(targetEntity=ResourceFile::class, mappedBy="resource", cascade={"persist", "remove"})
     */
    private $resourceFiles;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_end;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isValidated;

    public function __construct()
    {
        $this->pathology = new ArrayCollection();
        $this->resourceFiles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Pathology[]
     */
    public function getPathology(): Collection
    {
        return $this->pathology;
    }

    public function addPathology(Pathology $pathology): self
    {
        if (!$this->pathology->contains($pathology)) {
            $this->pathology[] = $pathology;
        }

        return $this;
    }

    public function removePathology(Pathology $pathology): self
    {
        $this->pathology->removeElement($pathology);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getResourceFormat(): ?ResourceFormat
    {
        return $this->resourceFormat;
    }

    public function setResourceFormat(?ResourceFormat $resourceFormat): self
    {
        $this->resourceFormat = $resourceFormat;

        return $this;
    }

    /**
     * @ORM\PrePersist()
     */
    public function onPrePersist()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }
    /**
     * Gets triggered only on update
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->updatedAt = new \DateTime();
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return Collection|ResourceFile[]
     */
    public function getResourceFiles(): Collection
    {
        return $this->resourceFiles;
    }

    public function addResourceFile(ResourceFile $resourceFile): self
    {
        if (!$this->resourceFiles->contains($resourceFile)) {
            $this->resourceFiles[] = $resourceFile;
            $resourceFile->setResource($this);
        }

        return $this;
    }

    public function removeResourceFile(ResourceFile $resourceFile): self
    {
        if ($this->resourceFiles->removeElement($resourceFile)) {
            // set the owning side to null (unless already changed)
            if ($resourceFile->getResource() === $this) {
                $resourceFile->setResource(null);
            }
        }

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(?\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }
}

src/Controller/BasketController.php
<?php

namespace App\Controller;

use App\Service\Basket\BasketService;
use App\Service\Stripe\StripeService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted ("ROLE_ENTERPRISE")
 * @Route("/panier", name="basket_")
 */
class BasketController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(BasketService $basketService, StripeService $stripeService): Response
    {
        $basketData = $basketService->getAllBasket();

        $total = $basketService->getTotal();

        return $this->render('basket/index.html.twig', [
            'products' => $basketData,
            'total' => $total,
        ]);
    }

    /**
     * @Route("/jsonStripe", name="jsonStripe")
     */
    public function jsonStripe(BasketService $basketService, StripeService $stripeService): Response
    {

        $account = $stripeService->getAccountId();

        $publicKey = $this->getParameter('api_public_key');

        $datas = ['publickey' => $publicKey, 'account' => $account];


        return new JsonResponse($datas, 200);
    }

    /**
     * @Route("/ajouter/{id}", name="add")
     */
    public function add(BasketService $basketService, int $id)
    {
        $basketService->add($id);

        return $this->redirectToRoute('basket_index');
    }

    /**
     * @Route("/supprimer/{id}", name="delete")
     */
    public function delete($id, BasketService $basketService)
    {
        $basketService->delete($id);

        return $this->redirectToRoute('basket_index');
    }
}

templates/basket/error.html.twig
{% extends 'base.html.twig' %}

{% block title %}Erreur de paiement{% endblock %}

{% block body %}
    <div class="pt-5">
        <h1 class="pt-5">Erreur survenue lors de votre achat</h1>
    </div>

{% endblock %}

templates/basket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Panier {% endblock %}

{% block body %}
    <div class="basket pt-5">
         <h1 class="pt-5 pb-4 text-center basket-title">Votre panier</h1>
        {% if products | length > 0 %}
        <table class="table">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.resource.name }}</td>
                        <td>{{ product.resource.price }}€</td>
                        <td>{{ product.quantity }}</td>
                        <td>{{ product.resource.price * product.quantity }}€</td>
                        <td>
                            <a href="{{path('basket_delete', {'id': product.resource.id}) }}" class="btn btn-danger btn-sm">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total: </td>
                    <td>{{ total }}€</td>
                    <td></td>
                </tr>

            </tfoot>
        </table>
        <div class="d-flex justify-content-center">
        <button id="checkout-button" class="btn btn-buy"><i class="fas fa-shopping-cart"></i> Acheter</button>
        </div>
        {% else %}
            <h3 class="text-center basket-empty">Votre panier est actuellement vide</h3>
            <a href="{{ path('knowledge_index') }}" class="return-knowledge">Retourner à la boutique</a>
        {% endif %}

    </div>


{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('stripe') }}
{% endblock %}

templates/basket/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement accepté{% endblock %}

{% block body %}
    <div class="pt-5 payment-success">
        <h1 class="pt-5 mb-5 text-center title-payment-success">Paiement accepté</h1>

        {% if purchased_resource is not empty %}
                {% if purchased_resource.resourceFiles is not empty %}
                    <h3 class="text-center mb-5">Ci-dessous le lien de téléchargement:</h3>
                {% for resourceFile in purchased_resource.resourceFiles %}
                    <a class="d-flex justify-content-center mb-5" href="/uploads/resources/{{ resourceFile.name }}" target="_blank"><i class="{{ resourceFile.resource.resourceFormat.icon }}"></i></a>
                {% endfor %}
                {% endif %}
                {% if purchased_resource.link is not empty %}
                    <h3 class="text-center mb-5">Lien à conserver (nous vous conseillons de le copier dans un de vos fichier car vous ne pourrez plus y accéder par la suite):</h3>
                    <a class="d-flex justify-content-center" href="{{ purchased_resource.link }}" target="_blank">{{ purchased_resource.link }}</a>
                {% endif %}
        {% endif %}
    </div>
{% endblock %}